### ISSUE TITLE
Linux - Link app does not close.

### ISSUE THREAD

**Issue by pablo-01** [civitai/civitai-link-desktop#38]
On Linux (installed using deb package) the app does not close on the 'x' button. There is no other way to close it other than killing all the processes.

**Comment by cmoody** [comment]
@pablo-01 if you right click or ctrl+click on the toolbar icon it should give you an option to Quit. For Mac and Windows we have the default behavior to minimize when clicking the X. Im not sure what the expected behavior is for Linux but have gone ahead and made that the default in the upcoming build.

**Comment by pablo-01** [comment]
Thanks, v1.15.1 would not close even when using Quit option from the toolbar. It would close the main window but the system icon would stay up as well ass all the processes would stay up. I have just updated to v1.15.2 and can confirm it now closes the app and all processes. 

Many thanks.
