### ISSUE TITLE
Question: Could this connect with a remote sd webui?

### ISSUE THREAD

**Issue by QureL** [civitai/civitai-link-desktop#43]
or it just supports local

**Comment by cmoody** [comment]
Hey @QureL, thanks for the inquiry. Can you expand a little on your use case? Right now you can run it on a remote system and download the files to that system. For example if you were running this on your Desktop, you could browse the site on your Mobile device and download files to your Desktop.

There has been a request to have a CLI version so it could be run on a cloud system. Right now though we do not have that on the road map. However since this is an open source project, we are always open to PRs.

**Comment by cmoody** [comment]
Not adding to road map at the moment but going to close and reference in https://github.com/civitai/civitai-link-desktop/issues/30 since I think the implementation would work in a similar way.
